.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE. 
.\" */
.\"
.TH "keentune-target.domain" "7" "6 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
keentune-target.domain - keentune-target domain file

.SH DESCRIPTION
This man page documents the format of the keentune-target domain file. The domain file mainly includes setparamall, getparamall, backup, and rollback functions. It contains the parameter domain definition and implementation, corresponding to the files in the /etc/keentune/parameter directory of keentuned.

.SH DOMAIN
At the moment we provide the following pre-defined domain:

.TP
.BI "iperf.py"
For iperf3 tuning task. The test environment requires both an iperf server and a client.
.TP
.BI "nginx.py"
For nginx tuning task. The test environment requires installing nginx and starting the service.
.TP
.BI "sysctl.py"
For tuning for operating system configuraions.
.TP
.BI "sysbench.py"
For tuning the performance of MySQL database.
.TP
.BI " fio.py"
For tuning hard disk data processing with the metric of IOPS. The test environment requires installing fio.

.SH FILES
.nf
.I /etc/keentune
.I /usr/lib/python3.6/site-packages/target/domain/

.SH "SEE ALSO"
.LP
keentune-target(8)
keentune-target.conf(5)

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
